### ISSUE TITLE
Proposal for `kittycad file view` command

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/cli#211]
When trying out the CLI for the first time, I wanted to check if file conversions worked but I don't have some of the software that some of those file types need to open. So I ended up having the [AutoDesk Online File Viewer](https://viewer.autodesk.com/designviews) open while I worked.

Since we will have pixel streaming possible from the engine with the work within KittyCAD/engine, I was wondering if it would be worthwhile for our users to have a way to view 3D models, for debugging or otherwise, within the terminal itself without too much effort. I think it fits our retro-with-superpowers brand.

## example usages
- `kittycad file view suzanne.step`: basic viewer, using something like https://github.com/hzeller/timg if the terminal supports it
- `kittycad file view --ascii`: display the video stream as ASCII characters. Idea from @alteous 

The UX of the viewer would be TBD, but maybe as an MVP a sensible default camera position is chosen, and no camera controls are given to the user. Eventually we could support keyboard combinations to pan, zoom, and orbit.

**Comment by pierremtb** [comment]
@franknoirot Stumbling on this now, I feel like this would also be super helpful to the Github Chrome extension? Would unlock major perf improvements and much larger file diffs

**Comment by pierremtb** [comment]
@franknoirot Yeah! All the mem intensive stuff basically. Combined diffs would have to require more work on the backend but would make a lot of sense too

**Comment by jessfraz** [comment]
once we have import in engine this is pretty easy with the same stuff as https://github.com/KittyCAD/cli/pull/312
