### ISSUE TITLE
Unread fields on rust 1.79

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/cli#686]
If you run `cargo +1.78 check` on this repo, it passes with 0 errors. But if you run `cargo +1.79 check` it'll fail.
<img width="487" alt="Screenshot 2024-06-15 at 7 35 37 PM" src="https://github.com/KittyCAD/cli/assets/5407457/265286ba-bd21-4c5b-a9c9-a667d71198a3">

<details>
  <summary>Click for plain text error</summary>
  
  ```
warning: field `description` is never read
  --> src/config.rs:49:9
   |
47 | pub struct ConfigOption {
   |            ------------ field in this struct
48 |     pub key: String,
49 |     pub description: String,
   |         ^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: field `tmp_file_override` is never read
  --> src/iostreams.rs:38:9
   |
11 | pub struct IoStreams {
   |            --------- field in this struct
...
38 |     pub tmp_file_override: Option<std::fs::File>,
   |         ^^^^^^^^^^^^^^^^^

warning: `zoo` (bin "zoo") generated 2 warnings
```
</details>

Weird. I guess the new rustc is smarter about finding dead code. We have to fix this to make CI pass again.

**Comment by adamchalmers** [comment]
@jessfraz should I just remove these fields or should I find a way to make them read?

**Comment by jessfraz** [comment]
Go ahead and delete

**Comment by jessfraz** [comment]
Well wait the config options do have descriptions so I guess on that one maybe we want to read rhem
